CREATE TABLE IF NOT EXISTS links(
    id VARCHAR(100) PRIMARY KEY,
    url VARCHAR(1000) NOT NULL
);

CREATE TABLE views(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    link_id VARCHAR(100) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    browser VARCHAR(255) NOT NULL,
    os VARCHAR(255) NOT NULL,
    countryISO VARCHAR(10) NOT NULL,
    countrySubdivisionISO VARCHAR(10) NOT NULL,
    access_at DATETIME NOT NULL
);